spring:
  application:
    name: Delivery-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/Bakery
    username: postgres
    password: ezio
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update 
    show-sql: true       
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server.port: 8086

eureka: 
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/